ClientInformationManager/Controllers/AddressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClientInformationManager.Controllers
{
    public class AddressController : Controller
    {
        Models.ClientInformationEntities db = new Models.ClientInformationEntities();
        // GET: Address
        public ActionResult Index(int id)
        {
            ViewBag.id = id;

            var theAddresses = db.PersonInformations.SingleOrDefault(c => c.person_id == id);
            return View(theAddresses);
        }

            // GET: Address/Details/5
        public ActionResult Details(int id)
        {
            Models.Address theAddress = db.Addresses.SingleOrDefault(a => a.address_id == id);
            return View(theAddress);
        }

        // GET: Address/Create
        public ActionResult Create(int id)
        {
            ViewBag.id = id;

            IEnumerable<SelectListItem> countries = db.Countries.Select(c => new SelectListItem()
            {
                Value = c.country_id.ToString(),
                Text = c.country_name
            });
            ViewBag.countries = countries;

            Models.PersonInformation person = db.PersonInformations.SingleOrDefault(c => c.person_id == id);
            return View();
        }

        // POST: Address/Create
        [HttpPost]
        public ActionResult Create(int id, FormCollection collection)
        {
          
            try
            {
                // TODO: Add insert logic here
                Models.Address address = new Models.Address()
                {
                    person_id = id,
                    description = collection["description"],
                    street_address = collection["street_address"],
                    city = collection["city"],
                    province_state = collection["province_state"],
                    zip_postal_code = collection["zip_postal_code"],
                    country_id = Int32.Parse(collection["country_id"])

                };

                db.Addresses.Add(address);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Address/Edit/5
        public ActionResult Edit(int id)
        {
            IEnumerable<SelectListItem> countries = db.Countries.Select(c => new SelectListItem()
            {
                Value = c.country_id.ToString(),
                Text = c.country_name
            });
            ViewBag.countries = countries;


            Models.Address theAddress = db.Addresses.SingleOrDefault(a => a.address_id == id);
            return View(theAddress);
        }

        // POST: Address/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                Models.Address theAddress = db.Addresses.SingleOrDefault(a => a.address_id == id);
                theAddress.city = collection["city"];
                theAddress.street_address = collection["street_address"];
                theAddress.description = collection["description"];
                theAddress.province_state = collection["province_state"];
                theAddress.zip_postal_code = collection["zip_postal_code"];
                theAddress.country_id = Int32.Parse(collection["country_id"]);
                db.SaveChanges();

                return RedirectToAction("Index", new { id = theAddress.person_id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Address/Delete/5
        public ActionResult Delete(int id)
        {
            Models.Address theAddress = db.Addresses.SingleOrDefault(p => p.address_id == id);
            return View(theAddress);
        }

        // POST: Address/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                Models.Address theAddress = db.Addresses.SingleOrDefault(p => p.address_id == id);
                db.Addresses.Remove(theAddress);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = theAddress.person_id });
            }
            catch
            {
                return View();
            }
        }
    }
}

ClientInformationManager/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClientInformationManager.Controllers
{
    public class ContactController : Controller
    {
        Models.ClientInformationEntities db = new Models.ClientInformationEntities();
        // GET: Contact
        public ActionResult Index(int id)
        {
            ViewBag.id = id;

            var theContacts = db.PersonInformations.SingleOrDefault(c => c.person_id == id);
            return View(theContacts);
        }

        // GET: Contact/Details/5
        public ActionResult Details(int id)
        {
            Models.ContactInformation theContact = db.ContactInformations.SingleOrDefault(c => c.contact_id == id);
            return View(theContact);
        }

        // GET: Contact/Create
        public ActionResult Create(int id)
        {
            ViewBag.id = id;
            Models.PersonInformation person = db.PersonInformations.SingleOrDefault(c => c.person_id == id);
            return View();
        }

        // POST: Contact/Create
        [HttpPost]
        public ActionResult Create(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                Models.ContactInformation newContact = new Models.ContactInformation()
                {
                    person_id = id,
                    type_of_info = collection["type_of_info"],
                    info = collection["info"]
                };

                db.ContactInformations.Add(newContact);
                db.SaveChanges();
                return RedirectToAction("Index", new { id =id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Contact/Edit/5
        public ActionResult Edit(int id)
        {
            Models.ContactInformation theContact = db.ContactInformations.SingleOrDefault(c => c.contact_id == id);
            return View(theContact);
        }

        // POST: Contact/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                Models.ContactInformation theContact = db.ContactInformations.SingleOrDefault(c => c.contact_id == id);

                theContact.type_of_info = collection["type_of_info"];
                theContact.info = collection["info"];

                db.SaveChanges();

                return RedirectToAction("Index", new { id = theContact.person_id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Contact/Delete/5
        public ActionResult Delete(int id)
        {
            Models.ContactInformation theContact = db.ContactInformations.SingleOrDefault(c => c.contact_id == id);
            return View(theContact);
        }

        // POST: Contact/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                Models.ContactInformation theContact = db.ContactInformations.SingleOrDefault(c => c.contact_id == id);

                db.ContactInformations.Remove(theContact);
                db.SaveChanges();

                return RedirectToAction("Index", new { id = theContact.person_id });
            }
            catch
            {
                return View();
            }
        }
    }
}

ClientInformationManager/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClientInformationManager.Controllers
{
    public class HomeController : Controller
    {
        Models.ClientInformationEntities db = new Models.ClientInformationEntities();
        // GET: Home
        public ActionResult Index()
        {
            return View(db.PersonInformations);
        }

        public ActionResult Search(string name)
        {
            var results = db.PersonInformations.Where(p => (p.first_name + p.last_name).Contains(name));
            return View(results);
        }

        // GET: Home/Details/5
        public ActionResult Details(int id)
        {
            Models.PersonInformation thePerson = db.PersonInformations.SingleOrDefault(p => p.person_id == id);
            return View(thePerson);
        }

        // GET: Home/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Home/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                Models.PersonInformation newPerson = new Models.PersonInformation();
                newPerson.first_name = collection["first_name"];
                newPerson.last_name = collection["last_name"];
                newPerson.notes = collection["notes"];
                newPerson.gender = collection["gender"];
                newPerson.profile_picture = 0;

                db.PersonInformations.Add(newPerson);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Home/Edit/5
        public ActionResult Edit(int id)
        {
            var thePerson = db.PersonInformations.SingleOrDefault(p => p.person_id == id);
            return View(thePerson);
        }

        // POST: Home/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                Models.PersonInformation thePerson = db.PersonInformations.SingleOrDefault(p => p.person_id == id);
                thePerson.first_name = collection["first_name"];
                thePerson.last_name = collection["last_name"];
                thePerson.notes = collection["notes"];
                thePerson.gender = collection["gender"];
                thePerson.profile_picture = 0;

                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Home/Delete/5
        public ActionResult Delete(int id)
        {
            Models.PersonInformation thePerson = db.PersonInformations.SingleOrDefault(p => p.person_id == id);
            return View(thePerson);
        }

        // POST: Home/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                Models.PersonInformation thePerson = db.PersonInformations.SingleOrDefault(p => p.person_id == id);

                db.Addresses.RemoveRange(thePerson.Addresses);
                db.Pictures.RemoveRange(thePerson.Pictures);
                thePerson.profile_picture = null;
                db.ContactInformations.RemoveRange(thePerson.ContactInformations);
                db.SaveChanges();

                db.PersonInformations.Remove(thePerson);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ClientInformationManager/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClientInformationManager.Controllers
{
    public class PictureController : Controller
    {
        Models.ClientInformationEntities db = new Models.ClientInformationEntities();
        // GET: Picture
        public ActionResult Index(int id)
        {
            ViewBag.id = id;

            var thePicture = db.PersonInformations.SingleOrDefault(c => c.person_id == id);
            return View(thePicture);
        }

        // GET: Picture/Details/5
        public ActionResult Details(int id)
        {
            Models.Picture thePicture = db.Pictures.SingleOrDefault(p => p.picture_id == id);
            return View(thePicture);
        }

        // GET: Picture/Create
        public ActionResult Create(int id)
        {
            ViewBag.id = id;
            Models.PersonInformation thePerson = db.PersonInformations.SingleOrDefault(p => p.person_id == id);
            return View();
        }

        // POST: Picture/Create
        [HttpPost]
        public ActionResult Create(int id, FormCollection collection, HttpPostedFileBase newPicture)
        {
            try
            {
                var type = newPicture.ContentType;
                string[] acceptableTypes = { "image/jpeg", "image/gif", "image/png" };
                if (newPicture != null && newPicture.ContentLength > 0 && acceptableTypes.Contains(type))
                {
                    Guid g = Guid.NewGuid();
                    string filename = g.ToString() + Path.GetExtension(newPicture.FileName);
                    string path = Path.Combine(Server.MapPath("~/Images/") + filename);
                    newPicture.SaveAs(path);
                    Models.Picture newPic = new Models.Picture()
                    {
                        caption = collection["Caption"],
                        path_of_picture = filename,
                        location_info = collection["Location"],
                        person_id = id,
                        time_info = collection["Time"]
                    };
                    db.Pictures.Add(newPic);
                    db.SaveChanges();
                }
                return RedirectToAction("Index", new { id = id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Picture/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Picture/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Picture/Delete/5
        public ActionResult Delete(int id)
        {
            Models.Picture thePicture = db.Pictures.SingleOrDefault(p => p.picture_id == id);
            return View(thePicture);
        }

        // POST: Picture/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                Models.Picture thePicture = db.Pictures.SingleOrDefault(p => p.picture_id == id);

                db.Pictures.Remove(thePicture);
                db.SaveChanges();

                return RedirectToAction("Index", new { id = thePicture.person_id });
            
            }
            catch
            {
                return View();
            }
        }
    }
}

ClientInformationManager/Views/Home/Create.cshtml
@model ClientInformationManager.Models.PersonInformation

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PersonInformation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.first_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.first_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.first_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.last_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.profile_picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.profile_picture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.profile_picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ClientInformationManager/Views/Home/Delete.cshtml
@model ClientInformationManager.Models.PersonInformation

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PersonInformation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.first_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.first_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.last_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.last_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.profile_picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.profile_picture)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ClientInformationManager/Views/Home/Details.cshtml
@model ClientInformationManager.Models.PersonInformation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PersonInformation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.first_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.first_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.last_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.last_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.profile_picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.profile_picture)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.person_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ClientInformationManager/Views/Home/Edit.cshtml
@model ClientInformationManager.Models.PersonInformation

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PersonInformation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.person_id)

        <div class="form-group">
            @Html.LabelFor(model => model.first_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.first_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.first_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.last_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.profile_picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.profile_picture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.profile_picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ClientInformationManager/Views/Home/Index.cshtml
@model IEnumerable<ClientInformationManager.Models.PersonInformation>

@{
    ViewBag.Title = "Index";
}

<form action="/Home/Search/" method="get">
    <label>Search for person: </label><input name="name" type="text" /><input type="submit"
                                                                              name="search" value="Search" />
</form>



<h2>Client Information Manager</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.first_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.last_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.notes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.profile_picture)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.first_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.last_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.notes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.profile_picture)
            </td>
            <td>
                @Html.ActionLink("Address Information", "Index", "Address", new { id = item.person_id }, null) |
                @Html.ActionLink("Contact Information", "Index", "Contact", new { id = item.person_id }, null) |
                @Html.ActionLink("Pictures", "Index", "Picture", new { id = item.person_id }, null) |
                @Html.ActionLink("Edit", "Edit", new { id = item.person_id }) |
                @Html.ActionLink("Details", "Details", new { id = item.person_id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.person_id })
            </td>
        </tr>
    }

</table>

ClientInformationManager/Views/Home/Search.cshtml
@model IEnumerable<ClientInformationManager.Models.PersonInformation>

@{
    ViewBag.Title = "IndexSearch";
}

<form action="/Home/Search/" method="get">
    <label>Search for person: </label><input name="name" type="text" /><input type="submit"
                                                                              name="search" value="Search" />
</form>



<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.first_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.last_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.notes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.profile_picture)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.first_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.last_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.notes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.profile_picture)
            </td>
            <td>
                @Html.ActionLink("Address Information", "Index", "Address", new { id = item.person_id }, null) |
                @Html.ActionLink("Contact Information", "Index", "Contact", new { id = item.person_id }, null) |
                @Html.ActionLink("Pictures", "Index", "Picture", new { id = item.person_id }, null) |
                @Html.ActionLink("Edit", "Edit", new { id = item.person_id }) |
                @Html.ActionLink("Details", "Details", new { id = item.person_id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.person_id })
            </td>
        </tr>
    }

</table>